include:
  - template: Security/SAST.gitlab-ci.yml

variables:
  VERSION: 1.0.${CI_PIPELINE_ID}

stages:
  - build
  - build_image
  - test
  - release

build-code:
  stage: build
  image: golang:1.17
  variables:
    GOPATH: $CI_PROJECT_DIR/backend/.go
  before_script:
    - mkdir -p backend/.go
  script:
    - cd backend/cmd/api/
    - go build .
    - mkdir -p $CI_PROJECT_DIR/momo-store-${VERSION}
    - mv api $CI_PROJECT_DIR/momo-store-${VERSION}/
  cache:
    key: $CI_COMMIT_REF_SLUG
    paths:
      - backend/.go/pkg/mod/
  artifacts:
    paths:
      - momo-store-${VERSION}/api

build-backend-docker:
  stage: build_image
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - mv momo-store-${VERSION}/api backend/
    - /kaniko/executor
      --context ${CI_PROJECT_DIR}/backend
      --dockerfile ${CI_PROJECT_DIR}/backend/Dockerfile
      --destination ${CI_REGISTRY_IMAGE}/momo-backend:${VERSION}
      --build-arg VERSION=${VERSION}
      --cache=true
      --cache-copy-layers

unit-test:
  stage: test
  image: golang:1.17
  variables:
    GOPATH: $CI_PROJECT_DIR/backend/.go
    GIT_DEPTH: "0"
  script:
    - cd backend
    - go test -v ./... 
  cache:
    key: $CI_COMMIT_REF_SLUG
    paths:
      - backend/.go/pkg/mod/

gosec-sast:
  stage: test
  variables:
    GOPATH: $CI_PROJECT_DIR/backend/.go
  before_script:
    - |
      cat <<EOF > ~/.netrc
      machine gitlab.praktikum-services.ru
      login $GITLAB_USER_LOGIN
      password $GITLAB_TOKEN
      EOF
  script:
    - /analyzer run --target-dir ${CI_PROJECT_DIR}/backend/
  cache:
    key: $CI_COMMIT_REF_SLUG
    paths:
      - backend/.go/pkg/mod/

#sonarqube-backend-sast:
#  stage: test
#  image: sonarsource/sonar-scanner-cli:latest
#  variables:
#    GIT_DEPTH: "0"
#  cache:
#    key: "${CI_JOB_NAME}"
#    paths:
#      - .sonar/cache
#  script:
#    - cd backend
#    - sonar-scanner -Dsonar.qualitygate.wait=true -Dsonar.host.url=${SONAR_URL} -Dsonar.login=${SONAR_LOGIN} -Dsonar.projectKey=${BACKEND_KEY}
#  allow_failure: true

upload-backend-nexus:
  stage: release
  variables:
    GIT_STRATEGY: none
  image:
    name: gcr.io/go-containerregistry/crane:debug
    entrypoint: [ "" ]
  cache: [ ]
  before_script:
    - crane auth login -u ${NEXUS_USER} -p ${NEXUS_PASSWORD} http://nexus.praktikum-services.tech/repository/momo-back-027-04/
  script:
    - crane tag ${CI_REGISTRY_IMAGE}/momo-backend:${VERSION} http://nexus.praktikum-services.tech/repository/momo-back-027-04/momo-backend:${VERSION}
    - crane push http://nexus.praktikum-services.tech/repository/momo-back-027-04/momo-backend:latest
