backend: 
  replicas: 3
  image:
    repository: 
    pullPolicy: IfNotPresent
  strategy:
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 20%
  revisionHistoryLimit: 12
  livenessProbe:
    initialDelaySeconds: 15
    periodSeconds: 30
    timeoutSeconds: 2
    failureThreshold: 6
  imagePullSecrets:
    name: docker-config-secret
  service:
    type: ClusterIP
    port: 8081
    targetPort: 8081
  secrets:
    dockerConfigSecret:
