deployment:
  replicas: 1
  revisionHistoryLimit: 12
  image: 
  imagePullPolicy: IfNotPresent
  volumeMounts:
    name: nginx-conf
    mountPath: /etc/nginx/conf.d/default.conf
    subPath: default.conf
  imagePullSecrets:
    name: docker-config-secret
configMap:
  name: default-conf
ingress:
  ingressClassName: frontend
  host: momo-k8s-027-04.ru
secrets:
  data:
    json: 
    type: kubernetes.io/dockerconfigjson
service:
  type: ClusterIP
  ports:
    port: 80
    protocol: TCP
    targetPort: 80
