---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.ports.port }}
      protocol: {{ .Values.service.ports.protocol }}
      targetPort: {{ .Values.service.ports.targetPort }}
  selector:
    app: frontend
